// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKKGISrBa0LqALY-p--_-McHzMvaRygE',
    appId: '1:407541343336:android:1293534aae4ddbcc26c7dd',
    messagingSenderId: '407541343336',
    projectId: 'love-to-chat-a2069',
    storageBucket: 'love-to-chat-a2069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDop7MFGriyfD4RG-L-YhCrxQU2MQRnfdM',
    appId: '1:407541343336:ios:f59ba6e8074ac83226c7dd',
    messagingSenderId: '407541343336',
    projectId: 'love-to-chat-a2069',
    storageBucket: 'love-to-chat-a2069.appspot.com',
    androidClientId: '407541343336-6f9vks4rvpd514drg1b7kvgsph1bvdfk.apps.googleusercontent.com',
    iosClientId: '407541343336-hd1k178lbbvulsdt3etad259rgvpmiho.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveToChat',
  );
}
